remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Learning Riemannian Metric Preserving Diffeomorphisms in Protein Dynamics
description: Geometric Deep Learning Workshop 2024 in Cambridge
show_downloads: false

authors:
  - name: Friso de Kruiff
    institution: Delft University of Technology
    institution: KTH Royal Institute of Technology
  - name: Willem Diepeveen
    institution: Cambridge University
  - name: Erik Bekkers
    institution: University of Amsterdam
  - name: Ozan Oktem
    institution: KTH Royal Institute of Technology
    
