remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Learning Riemannian Metric Preserving Diffeomorphisms in Protein Dynamics
description: Geometric Deep Learning Workshop 2024 in Cambridge
show_downloads: false

authors:
  - name: "Friso de Kruiff"
    institutions:
      - name: "Delft University of Technology"
      - name: "KTH Royal Institute of Technology"
  - name: "Willem Diepeveen"
    institutions:
      - name: "Cambridge University"
  - name: "Erik Bekekrs"
    institutions:
      - name: "University of Amsterdam"
  - name: "Ozan Öktem"
    institutions:
      - name: "KTH Royal Institute of Technology"
