remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Learning Riemannian Metric Preserving Diffeomorphisms in Protein Dynamics
description: Geometric Deep Learning Workshop 2024 in Cambridge
show_downloads: false

authors:
  - name: Author 1
    index: 1
    institution: Institution A
  - name: Author 2
    index: 2
    institution: Institution B
  # Add more authors as needed

institutions:
  - name: Institution A
    index: A
  - name: Institution B
    index: B
  # Add more institutions as needed
