remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Learning Riemannian Metric Preserving Diffeomorphisms in Protein Dynamics
description: Geometric Deep Learning Workshop 2024 in Cambridge
show_downloads: false

authors:
  - name: "Friso de Kruiff"
    index: 1
    institution: "Delft University of Technology"
  - name: "Willem Diepeveen"
    index: 2
    institution: 
  - name: "Erik Bekekrs"
    index: 3
    institution: "University of Amsterdam"
  - name: "Ozan Öktem"
    index: 4
    institution: "KTH Royal Institute of Technology"

institutions:
  - name: Delft University of Technology
    index: A
  - name: KTH Royal Institute of Technology
    index: B
  - name: Cambridge University
    index: C
  - name: University of Amsterdam
    index: D
  # Add more institutions as needed

