remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Learning Riemannian Metric Preserving Diffeomorphisms in Protein Dynamics
description: Geometric Deep Learning Workshop 2024 in Cambridge
show_downloads: false

authors:
  - name: "Friso de Kruiff"
    institutions: 
      - "Delft University of Technology"
      - "KTH Royal Institute of Technology"
  - name: "Willem Diepeveen"
    institutions: 
      - "Cambridge University"
  - name: "Erik Bekkers"
    institutions: 
      - "University of Amsterdam"
  - name: "Ozan Öktem"
    institutions:  # Fixed the key name here
      - "KTH Royal Institute of Technology"  # Fixed the typo in institution(s)

institutions:
  - name: "Delft University of Technology" 
  - name: "KTH Royal Institute of Technology"
  - name: "Cambridge University"
  - name: "University of Amsterdam"
