remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Learning Riemannian Metric Preserving Diffeomorphisms in Protein Dynamics
description: Geometric Deep Learning Workshop 2024 in Cambridge
author: Friso de Kruiff Willem Diepeveen Ozan \"Oktem Erik Bekker
show_downloads: false
