remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Learning Riemannian Metric Preserving Diffeomorphisms in Protein Dynamics
description: Geometric Deep Learning Workshop 2024 in Cambridge
show_downloads: false

authors:
  - name: "Author One"
    institution: "Institution One"
  - name: "Author Two"
    institution: "Institution Two"
  - name: "Author Three"
    institution: "Institution Three"
